GET http://localhost:9000/api/items

###

GET http://localhost:3000/users/5ee4df5530e0b04840dd2835

###

POST http://localhost:9000/api/users/register
Content-Type: application/json

{
  "name": "Hash User5",
  "email": "joni@abv.bg",
  "password": "12345asdasdasdasas",
  "verifyPassword": "12345asdasdasdasas",
  "isAdmin": true
}

###

POST http://localhost:9000/api/users/login
Content-Type: application/json

{
  "email": "lyubomir.vaklinov@gmail.com",
  "password": "1234PassWord##"
}

###

DELETE http://localhost:3000/api/users/delete

###

PATCH http://localhost:3000/users/5ee4c51ab4694c39e7a89207
Content-Type: application/json

{
  "name": "John"
}

###

POST http://localhost:3000/items
Content-Type: application/json

{
  "title": "New Item",
  "description": "Blaaaaa"
}